version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: aicybertool-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: aicybertool
      RABBITMQ_DEFAULT_PASS: aicybertool123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - aicybertool-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: aicybertool-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aicybertool-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

networks:
  aicybertool-network:
    driver: bridge
